# Site settings
title: A blog about Harper Hwang
description: A blog about Harper Hwang
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Harper Hwang
user_description: A Common Young Programmer. I am interested in python programming, trying to get more professional skills(Also C# and etc...). I want to be a Dreaming, Eternal-Young-Sensed programmer.
user_title: Software Developer
email: 444.gkk@gmail.com
twitter_username: profile.php?id=100013468268325
github_username:  Nyamcat
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
